# GCP Infrastructure for OWASP ZAP Cloud Scanning
# Creates ephemeral infrastructure for running ZAP in Docker

terraform {
  required_version = ">= 1.0.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "google" {
  project     = var.project_id
  region      = var.region
  zone        = var.zone
  credentials = file(var.credentials_file)
}

# Generate a unique identifier for this scan
resource "random_id" "scan_id" {
  byte_length = 4
}

locals {
  scan_identifier = "kast-zap-${random_id.scan_id.hex}"
  common_labels = merge(
    var.labels,
    {
      scan_id   = random_id.scan_id.hex
      timestamp = replace(timestamp(), ":", "-")
    }
  )
}

# VPC Network
resource "google_compute_network" "zap_network" {
  name                    = "${local.scan_identifier}-network"
  auto_create_subnetworks = false

  labels = local.common_labels
}

# Subnet
resource "google_compute_subnetwork" "zap_subnet" {
  name          = "${local.scan_identifier}-subnet"
  ip_cidr_range = "10.0.1.0/24"
  region        = var.region
  network       = google_compute_network.zap_network.id
}

# Firewall rule for SSH
resource "google_compute_firewall" "zap_ssh" {
  name    = "${local.scan_identifier}-allow-ssh"
  network = google_compute_network.zap_network.name

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["0.0.0.0/0"] # TODO: Restrict to operator IP
  target_tags   = ["zap-scanner"]
}

# Firewall rule for ZAP API
resource "google_compute_firewall" "zap_api" {
  name    = "${local.scan_identifier}-allow-zap-api"
  network = google_compute_network.zap_network.name

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }

  source_ranges = ["0.0.0.0/0"] # TODO: Restrict to operator IP
  target_tags   = ["zap-scanner"]
}

# Firewall rule for outbound traffic
resource "google_compute_firewall" "zap_egress" {
  name      = "${local.scan_identifier}-allow-egress"
  network   = google_compute_network.zap_network.name
  direction = "EGRESS"

  allow {
    protocol = "all"
  }

  destination_ranges = ["0.0.0.0/0"]
  target_tags        = ["zap-scanner"]
}

# External IP address
resource "google_compute_address" "zap_ip" {
  name   = "${local.scan_identifier}-ip"
  region = var.region

  labels = local.common_labels
}

# Startup script for Docker, nginx, and ZAP installation
locals {
  startup_script = <<-EOF
#!/bin/bash
set -e

# Log all output
exec > >(tee -a /var/log/zap-setup.log)
exec 2>&1

echo "Starting ZAP cloud setup at $$(date)"

# Update system
echo "Updating system packages..."
apt-get update
apt-get upgrade -y

# Create swap file for memory-intensive ZAP operations
echo "Configuring swap file..."
if ! swapon --show | grep -q '/swapfile'; then
    echo "Creating 4GB swap file..."
    
    # Check available disk space
    available_space=$$(df / | awk 'NR==2 {print int($$4/1024/1024)}')
    if [ $$available_space -lt 5 ]; then
        echo "WARNING: Insufficient disk space for swap file (available: $${available_space}GB)"
    else
        # Create swap file
        if ! fallocate -l 4G /swapfile 2>/dev/null; then
            echo "fallocate failed, using dd instead..."
            dd if=/dev/zero of=/swapfile bs=1G count=4 status=progress
        fi
        
        # Set correct permissions
        chmod 600 /swapfile
        
        # Set up swap area
        mkswap /swapfile
        
        # Enable swap
        swapon /swapfile
        
        # Add to /etc/fstab for persistence
        if ! grep -q "/swapfile" /etc/fstab; then
            echo "/swapfile none swap sw 0 0" >> /etc/fstab
        fi
        
        echo "Swap file created and enabled:"
        swapon --show
    fi
else
    echo "Swap already configured, skipping"
    swapon --show
fi

# Install Docker using official installation script (more reliable)
echo "Installing Docker using official script..."
curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
sh /tmp/get-docker.sh
rm /tmp/get-docker.sh

# Verify Docker installation
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker installation failed"
    exit 1
fi

echo "Docker version: $$(docker --version)"

# Start Docker service
echo "Starting Docker service..."
systemctl start docker
systemctl enable docker

# Add ubuntu user to docker group for non-root access
usermod -aG docker ubuntu 2>/dev/null || true

# Install nginx for reverse proxy
echo "Installing nginx..."
apt-get install -y nginx

# Create nginx configuration for ZAP reverse proxy
# Configuration based on kast/config/nginx/zap-proxy.conf
echo "Configuring nginx reverse proxy..."
cat > /etc/nginx/sites-available/zap-proxy << 'NGINX_EOF'
# NGINX Reverse Proxy Configuration for OWASP ZAP
# Auto-generated by KAST Terraform (GCP)
# Based on: kast/config/nginx/zap-proxy.conf

server {
    listen 8080;
    server_name _;

    # Logging (optional - disable for production if needed)
    access_log /var/log/nginx/zap-access.log;
    error_log /var/log/nginx/zap-error.log;

    location / {
        # Proxy to ZAP on internal port
        proxy_pass http://localhost:8081;

        # Force HTTP/1.1 for better compatibility
        proxy_http_version 1.1;

        # Clear connection header to prevent connection reuse issues
        proxy_set_header Connection "";

        # CRITICAL: Rewrite Host header with port to avoid ZAP proxy loop
        # ZAP requires the port number to distinguish API requests from proxy requests
        # Without this, ZAP may treat API calls as proxy requests, causing failures
        proxy_set_header Host localhost:8081;

        # Make requests appear strictly local to ZAP
        # This prevents ZAP from treating external IPs as proxy targets
        proxy_set_header X-Real-IP 127.0.0.1;
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-Host localhost;

        # Increase timeouts for long-running ZAP operations
        # ZAP scans can take minutes to hours depending on target complexity
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        # Allow large request bodies for scan configurations and file uploads
        client_max_body_size 10M;

        # Disable buffering for better streaming of scan progress
        # This allows real-time progress updates via ZAP API
        proxy_buffering off;
        proxy_request_buffering off;
    }
}
NGINX_EOF

# Enable the site
ln -sf /etc/nginx/sites-available/zap-proxy /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test nginx configuration
nginx -t

# Start and enable nginx
systemctl start nginx
systemctl enable nginx

echo "Nginx configured and started"

# Create directories for ZAP
echo "Creating ZAP directories..."
mkdir -p /opt/zap/{config,reports}
chmod -R 777 /opt/zap

# Pull ZAP Docker image
echo "Pulling ZAP Docker image: ${var.zap_docker_image}"
docker pull ${var.zap_docker_image}

# Start ZAP container on internal port 8081 (nginx will proxy to it)
echo "Starting ZAP container on internal port 8081..."
docker run -d \
  --name kast-zap \
  --restart unless-stopped \
  -u zap \
  -p 127.0.0.1:8081:8081 \
  -v /opt/zap/reports:/zap/reports:rw \
  -e TZ=UTC \
  --health-cmd="curl -f http://localhost:8081/JSON/core/view/version/?apikey=${var.zap_api_key} || exit 1" \
  --health-interval=30s \
  --health-timeout=10s \
  --health-retries=3 \
  --health-start-period=60s \
  ${var.zap_docker_image} \
  zap.sh -daemon \
  -host 0.0.0.0 \
  -port 8081 \
  -config api.key=${var.zap_api_key} \
  -config api.addrs.addr.name=.* \
  -config api.addrs.addr.regex=true \
  -config api.disablekey=false

# Wait for ZAP to be ready
echo "Waiting for ZAP to start..."
for i in {1..30}; do
  if docker exec kast-zap curl -f http://localhost:8081/JSON/core/view/version/?apikey=${var.zap_api_key} >/dev/null 2>&1; then
    echo "ZAP is ready!"
    break
  fi
  echo "Waiting for ZAP... ($i/30)"
  sleep 10
done

# Verify container is running
if docker ps | grep -q kast-zap; then
  echo "ZAP container is running successfully"
  docker ps --filter name=kast-zap --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
else
  echo "ERROR: ZAP container failed to start"
  docker logs kast-zap
  exit 1
fi

# Create ready flag
touch /tmp/zap-ready

echo "ZAP cloud setup completed at $$(date)"
echo "ZAP API URL: http://$$(curl -s -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip):8080"
echo "ZAP API Key: ${var.zap_api_key}"
  EOF
}

# Compute Instance (Preemptible/Spot)
resource "google_compute_instance" "zap_instance" {
  name         = "${local.scan_identifier}-instance"
  machine_type = var.machine_type
  zone         = var.zone

  # Preemptible instance (spot)
  scheduling {
    preemptible                 = var.use_preemptible_instance
    automatic_restart           = false
    on_host_maintenance         = "TERMINATE"
    provisioning_model          = var.use_preemptible_instance ? "SPOT" : "STANDARD"
    instance_termination_action = var.use_preemptible_instance ? "DELETE" : null
  }

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2204-lts"
      size  = 30
      type  = "pd-standard"
    }
    auto_delete = true
  }

  network_interface {
    network    = google_compute_network.zap_network.name
    subnetwork = google_compute_subnetwork.zap_subnet.name

    access_config {
      nat_ip = google_compute_address.zap_ip.address
    }
  }

  metadata = {
    ssh-keys       = "ubuntu:${var.ssh_public_key}"
    startup-script = local.startup_script
  }

  tags = ["zap-scanner"]

  labels = local.common_labels
}
